# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70d346b9a1afb277f6b88980ed723925e4f52a282ea88745683373b6036b91c2790ffe3225ce4f9de9e9f0976a11cbd2f413804b6aaf9fa63509d6c152d84e5e

test:
  secret_key_base: c82044693e94874f6ae5364875a05cdd816588561bd9b936a451f77f3af29560f5e164e90c459e8f8669f688acde7c53a1d5ca7c5f1266f2eb2fc32f1dd5b873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
